FROM python:3.10-slim-buster

#inside container
#make a new folder inside container
WORKDIR /backend-flask

#outside container -> inside container
# this contains the libraries wan to install to run the app
COPY requirements.txt requirements.txt

#inside container
# this contains the libraries used for the app
RUN pip3 install -r requirements.txt

#outside container -> inside container
#means everything in the current directory
#first period. /backend-flask (outside container)
# second period ./backend-flask (inside container)
COPY . .

#set environment variables (env vars) 
#inside containers and will remain set when the container is running
ENV FLASK_ENV=development

EXPOSE ${PORT}

#CMD (command)
#python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]
